# Generated by Django 2.2.7 on 2019-11-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
