# Generated by Django 2.2.7 on 2019-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191114_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sandwitch', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('bread', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
            ],
        ),
    ]
